name: On merge to main, build the protocol and add it to the website "Log RECENT_MERGED_BRANCH_NAME"

on:
  push:
    branches:
     - main

jobs:
  build-website:
    runs-on: ubuntu-latest
    name: "add protocol to website"
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - uses: tonynguyenit18/github-action-custom-vars@v1
      - name: test
        run: |
          echo 'GitHub actions:' $GITHUB_ACTIONS
          echo 'Event name:' $GITHUB_EVENT_NAME
          echo 'ref:' $GITHUB_REF
          echo 'recent merged branch:' $RECENT_MERGED_BRANCH_NAME
